// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// enrichment_test_simulation
DataFrame enrichment_test_simulation(Rcpp::List DB_of_categories, std::vector<std::string> list_of_all_genes, std::vector<std::string> pool, int selectSize, int steps, unsigned int randomSeed);
RcppExport SEXP _MulEA_enrichment_test_simulation(SEXP DB_of_categoriesSEXP, SEXP list_of_all_genesSEXP, SEXP poolSEXP, SEXP selectSizeSEXP, SEXP stepsSEXP, SEXP randomSeedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type DB_of_categories(DB_of_categoriesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type list_of_all_genes(list_of_all_genesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type pool(poolSEXP);
    Rcpp::traits::input_parameter< int >::type selectSize(selectSizeSEXP);
    Rcpp::traits::input_parameter< int >::type steps(stepsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type randomSeed(randomSeedSEXP);
    rcpp_result_gen = Rcpp::wrap(enrichment_test_simulation(DB_of_categories, list_of_all_genes, pool, selectSize, steps, randomSeed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MulEA_enrichment_test_simulation", (DL_FUNC) &_MulEA_enrichment_test_simulation, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_MulEA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
